site_name: 'Poseidon Documentation'
repo_url: 'https://github.com/luhang-HPU/poseidon-docs'
site_author: 'LuHang'
copyright: '2023, LuHang'
docs_dir: 'docs'
site_dir: 'site'
extra:
    version: 1.0

theme: 
#    name: 'material'
    name: 'readthedocs'
    logo: './Image/Logo/logoR.png'


# plugins:
#   - search
#   - awesome-pages


markdown_extensions:
    - toc:
        permalink: true
    - pymdownx.highlight:  # 代码高亮
        anchor_linenums: true
    - pymdownx.arithmatex

extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

nav:
    - Home: './index.md'
    - OVERVIEW:
        - Poseidon Introduction: './Overview/Poseidon_Basics.md'
        - Homomorphic Computing Unit (HPU): './Overview/HPU.md'
    - GETTING STARTED:
        - Compile and Installation:
            - Software Library: './Getting_Started/Compile and Installation/Software(poseidon).md'
            - Hardware Library: './Getting_Started/Compile and Installation/Hardware(poseidon with HPU).md'
        - API:
            - Basics: './Getting_Started/API/Basic API.md'
            - BFV: './Getting_Started/API/FHE schemes/BFV API.md'
            - BGV: './Getting_Started/API/FHE schemes/BGV API.md'
            - CKKS: './Getting_Started/API/FHE schemes/CKKS API.md'
        - Programming:
            - How to Program: './Getting_Started/Programming/How to Program.md'
            - Examples: './Getting_Started/Programming/Examples.md'
    - Benchmark:
        - Introduction: './Benchmark/Introduction.md'
        - Download and Compile: './Benchmark/Trident Installation.md'
        - Application:
            - Framingham Heart Study: './Benchmark/Framingham.md'
            - Private Information Retrieval (PIR): './Benchmark/pir_bfv.md'
            - Private Set Intersection (PSI): './Benchmark/PSI.md'
            - Logistic Regression Train (LR Train): './Benchmark/LR Train.md'
            - K-Nearest Neighbor (KNN): './Benchmark/knn.md'
